name: moduleindex

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  tfmoduleindex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        
      - name: Generate Terraform Modules Index and inject in README.md
        run: $GITHUB_ACTION_PATH/scripts/gen_tfmoduleindex.sh

      - name: Git status
        id: git_status
        shell: bash
        run: |
          if [[ -n $(git status --porcelain) ]]; then
          git diff
          echo "module_updates=$(git status --porcelain | wc -l)" | tee -a $GITHUB_OUTPUT
          
      - name: Create Pull Request
        id: cpr
        if: >-
          steps.git_status.outputs.module_updates > 0
        uses: peter-evans/create-pull-request@v6
        with:
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          commit-message: "Auto-generate moduleindex by GitHub Actions"
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          add-paths: ./README.md
          title: Auto-Update Terraform Modules Index in README
          body: |
            ---
            Good news everyone,
            
            There is a new terraform module!
            
            Let's update that in README.md.
            
            ---
            🤖 I am a bot, beep beep.
          branch: autoupdate-readme
          base: main
          delete-branch: true
      
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
