# This is a basic workflow that is manually triggered

name: moduleindex

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  moduleindex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
      - name: Generate Terraform Modules Index and inject in README.md
        shell: bash
        run: $PWD/scripts/module_index.sh

      - name: Print Readme
        shell: bash
        run: cat $PWD/README.md

      - name: Git status
        id: git_status
        shell: bash
        run: |
          if [[ -n $(git status --porcelain) ]]; then
          echo "true"
          else
          echo "false"
          fi

      - name: Commit changes in Readme
        id: git_commit
        if: steps.git_status.outputs == 'true'
        shell: bash
        run: |
          if [[ -n $(git status --porcelain) ]]; then
          git status
          git add .
          git commit -m "Auto-generate moduleindex by GitHub Actions"
          echo "Changes have been commited"
          else
          echo "No changes detected."
          fi
          
      - name: Create Pull Request
        id: cpr
        if: steps.git_commit.outputs == 'Changes have been commited'
        uses: peter-evans/create-pull-request@v6
        with:
          title: Auto-Update Terraform Modules Index in README
          body: |
            Good news everyone,
            There is a new terraform module!
            Let's update that in README.md.
            ---
            🤖 I am a bot, beep beep.
          branch: update-readme/$(date +'%Y%m%d%H%M%S')
          base: master
      
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
